# This is a basic workflow to help you get started with Actions

name: Publish Releases

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要发布的 Tag'
        required: true
        type: string
        default: 'v1.0.0'

      publish-to-modrinth:
        description: '是否发布到 Modrinth'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Get Latest Tag
      #   id: get_tag
      #   run: |
      #     echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      #     echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Create Tag
        run: git tag ${{ inputs.tag }}
        continue-on-error: false

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Generate zip file And Next Changelog
        run: |
            python3 generate.py -v classic
            python3 generate.py -v neo
            python3 precreate_changelog.py

      - name: Check changelog
        id: check_changelog
        run: |
          if [ ! -f ./.github/changelog/${{ inputs.tag }}-changelog.md ]; then
            echo "Changelog file not found"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: masa-mods-chinese.zip
          path: |
            ./masa-mods-chinese.zip
            ./.github/changelog/${{ inputs.tag }}-changelog.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          draft: false
          prerelease: false
          body_path: "./.github/changelog/${{ inputs.tag }}-changelog.md"

      - name: Upload old version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./masa-mods-chinese.zip
          asset_name: masa-mods-chinese.zip
          asset_content_type: application/zip

      - name: Upload new version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./masa-mods-chinese-neo.zip
          asset_name: masa-mods-chinese-neo.zip
          asset_content_type: application/zip

  modrinth_publish:
    name: Publish to Modrinth
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: masa-mods-chinese.zip

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: qloCzEiA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ${{ inputs.tag }}
          version: Masa 模组翻译包 ${{ inputs.tag }}
          version-type: release
          game-versions: 1.21.x
          changelog: '.github/changelog/${{ inputs.tag }}-changelog.md'
          files: ./masa-mods-chinese.zip
          loaders: minecraft
